version: "3.8"

services:
  node1:
    image: til-akka-typed
    container_name: node1
    platform: linux/amd64
    environment:
      SEED_NODES.0: "akka://ClusterSystem@node1:2551"
      SEED_NODES.1: "akka://ClusterSystem@node2:2552"
      SEED_NODES.2: "akka://ClusterSystem@node3:2553"
      SEED_HOST: "node1"
      SEED_PORT: 2551
      HTTP_PORT: 8080
    ports:
      - "8080:8080"
    networks:
      - backend-network

  node2:
    image: til-akka-typed
    container_name: node2
    platform: linux/amd64
    environment:
      SEED_NODES.0: "akka://ClusterSystem@node1:2551"
      SEED_NODES.1: "akka://ClusterSystem@node2:2552"
      SEED_NODES.2: "akka://ClusterSystem@node3:2553"
      SEED_HOST: "node2"
      SEED_PORT: 2552
      HTTP_PORT: 8081
    ports:
      - "8081:8081"
    networks:
      - backend-network

  node3:
    image: til-akka-typed
    container_name: node3
    platform: linux/amd64
    environment:
      SEED_NODES.0: "akka://ClusterSystem@node1:2551"
      SEED_NODES.1: "akka://ClusterSystem@node2:2552"
      SEED_NODES.2: "akka://ClusterSystem@node3:2553"
      SEED_HOST: "node3"
      SEED_PORT: 2553
      HTTP_PORT: 8082
    ports:
      - "8082:8082"
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
