version: "3.8"

# アンカーを用いてすべてのコンテナに共通の環境変数をまとめて定義する
x-environment: &seed-nodes-environment
  SEED_NODES.0: "akka://ClusterSystem@node1:2551"
  SEED_NODES.1: "akka://ClusterSystem@node2:2552"
  SEED_NODES.2: "akka://ClusterSystem@node3:2553"

services:
  node1:
    image: til-akka-typed
    env_file:
      - ./.env/.env.test
    container_name: node1
    platform: linux/arm64
    environment:
      <<: *seed-nodes-environment
      SEED_HOST: "node1"
      SEED_PORT: 2551
      HTTP_PORT: 8080
    ports:
      - "8080:8080"
    volumes:
      - "./target/snapshots:/target/snapshots"
    networks:
      - backend-network

  node2:
    image: til-akka-typed
    env_file:
      - ./.env/.env.test
    container_name: node2
    platform: linux/arm64
    environment:
      <<: *seed-nodes-environment
      SEED_HOST: "node2"
      SEED_PORT: 2552
      HTTP_PORT: 8081
    ports:
      - "8081:8081"
    volumes:
      - "./target/snapshots:/target/snapshots"
    networks:
      - backend-network

  node3:
    image: til-akka-typed
    env_file:
      - ./.env/.env.test
    container_name: node3
    platform: linux/arm64
    environment:
      <<: *seed-nodes-environment
      SEED_HOST: "node3"
      SEED_PORT: 2553
      HTTP_PORT: 8082
    ports:
      - "8082:8082"
    volumes:
      - "./target/snapshots:/target/snapshots"
    networks:
      - backend-network

  dynamodb:
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb
    expose:
      - "8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -inMemory"
    volumes:
      - ./target/persistence/dynamodb/data:/data
    networks:
      - backend-network

  dynamodb-admin:
    container_name: dynamodb-admin
    image: aaronshaf/dynamodb-admin:latest
    environment:
      - DYNAMO_ENDPOINT=dynamodb:8000
    ports:
      - 8001:8001
    depends_on:
      - dynamodb
    networks:
      - backend-network

  dynamosetup:
    image: infrastructureascode/aws-cli
    env_file:
      - ./.env/.env.test
    environment:
      LOCALSTACK_HOST: "dynamodb"
      DDB_PORT: 8000
    entrypoint: /scripts/dynamodb/entrypoint.sh
    volumes:
      - "./scripts/dynamodb:/scripts/dynamodb"
    depends_on:
      - dynamodb
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
