apiVersion: apps/v1
kind: Deployment
metadata:
  name: til-akka-typed-deployment
spec:
  selector:
    matchLabels:
      app: node1
  replicas: 1
  template:
    metadata:
      labels:
        app: node1
    spec:
      containers:
        - name: node1
          image: kuramapommel/til-akka-typed:latest
          ports:
            - containerPort: 8080
          env:
            - name: SEED_HOST
              value: "0.0.0.0"
            - name: SEED_PORT
              value: "2551"
            - name: HTTP_PORT
              value: "8080"
            - name: SEED_NODES.0
              value: "akka://ClusterSystem@0.0.0.0:2551"
            - name: SEED_NODES.1
              value: "akka://ClusterSystem@0.0.0.0:2552"
            - name: SEED_NODES.2
              value: "akka://ClusterSystem@0.0.0.0:2553"

---
apiVersion: v1
kind: Service
metadata:
  name: til-akka-typed-service
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      nodePort: 30080
  selector:
    app: node1

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dynamodb-local-deployment
spec:
  selector:
    matchLabels:
      app: dynamodb-local
  replicas: 1
  template:
    metadata:
      labels:
        app: dynamodb-local
    spec:
      containers:
        - name: dynamodb-local
          image: amazon/dynamodb-local:latest
          ports:
            - containerPort: 8000
          args: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-inMemory"]

---
apiVersion: v1
kind: Service
metadata:
  name: dynamodb-local-service
spec:
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      nodePort: 30000
  selector:
    app: dynamodb-local
