apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: til-akka-typed-stateful-set
spec:
  selector:
    matchLabels:
      app: node1
  serviceName: "til-akka-typed-service"
  replicas: 3
  template:
    metadata:
      labels:
        app: node1
    spec:
      containers:
        - name: node1
          image: kuramapommel/til-akka-typed:latest
          ports:
            - containerPort: 8080
          env:
            - name: HOST_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: SEED_PORT
              value: "2551"
            - name: HTTP_PORT
              value: "8080"
            - name: SEED_NODES.0
              value: "akka://ClusterSystem@til-akka-typed-stateful-set-0.til-akka-typed-service:2551"
            - name: SEED_NODES.1
              value: "akka://ClusterSystem@til-akka-typed-stateful-set-1.til-akka-typed-service:2551"
            - name: SEED_NODES.2
              value: "akka://ClusterSystem@til-akka-typed-stateful-set-2.til-akka-typed-service:2551"
            - name: DYNAMODB_HOST
              value: "dynamodb-local-service.default.svc.cluster.local"
            - name: DYNAMODB_PORT
              value: "8000"
          command: ["bash", "-c"]
          args:
            - export SEED_HOST=${HOST_NAME}.til-akka-typed-service;
              java -Dconfig.resource=/persistence_docker-compose.conf -jar /app/til-akka-typed.jar;

---
apiVersion: v1
kind: Service
metadata:
  name: til-akka-typed-service
spec:
  clusterIP: None
  ports:
    - port: 2551
      targetPort: 2551
      protocol: TCP
  selector:
    app: node1

---
apiVersion: v1
kind: Service
metadata:
  name: til-akka-typed-api-service
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      nodePort: 30080
  selector:
    app: node1

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dynamodb-local-deployment
spec:
  selector:
    matchLabels:
      app: dynamodb-local
  replicas: 1
  template:
    metadata:
      labels:
        app: dynamodb-local
    spec:
      containers:
        - name: dynamodb-local
          image: amazon/dynamodb-local:latest
          ports:
            - containerPort: 8000
          args: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-inMemory"]
          volumeMounts:
            - mountPath: /data
              name: data-volume
      volumes:
        - name: data-volume
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: dynamodb-local-service
spec:
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      nodePort: 30000
  selector:
    app: dynamodb-local

---
apiVersion: v1
kind: Pod
metadata:
  name: dynamodb-setup-pod
  labels:
    app: dynamodb-setup-pod
spec:
  restartPolicy: Never # 再起動しない設定
  containers:
    - name: dynamodb-setup
      image: infrastructureascode/aws-cli
      env:
        - name: AWS_ACCESS_KEY_ID
          value: "DUMMYAWSACCESSKEYID"
        - name: AWS_SECRET_ACCESS_KEY
          value: "DUMMYAWSSECRETACCESSKEY"
        - name: AWS_DEFAULT_REGION
          value: "us-east-1"
        - name: AWS_REGION
          value: "us-east-1"
        - name: LOCALSTACK_HOST
          value: "dynamodb-local-service.default.svc.cluster.local"
        - name: DDB_PORT
          value: "8000"
      volumeMounts:
        - name: scripts-volume
          mountPath: /scripts/dynamodb
      command: ["/scripts/dynamodb/entrypoint.sh"]
  volumes:
    - name: scripts-volume
      hostPath:
        path: "/scripts/dynamodb"
        type: Directory

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dynamodb-admin-deployment
spec:
  selector:
    matchLabels:
      app: dynamodb-admin
  replicas: 1
  template:
    metadata:
      labels:
        app: dynamodb-admin
    spec:
      containers:
        - name: dynamodb-admin
          image: aaronshaf/dynamodb-admin:latest
          ports:
            - containerPort: 8001
          env:
            - name: DYNAMO_ENDPOINT
              value: "dynamodb-local-service.default.svc.cluster.local:8000"

---
apiVersion: v1
kind: Service
metadata:
  name: dynamodb-admin-service
spec:
  type: NodePort
  ports:
    - port: 8001
      targetPort: 8001
      protocol: TCP
      nodePort: 30001
  selector:
    app: dynamodb-admin
