apiVersion: v1
kind: Service
metadata:
  name: til-akka-typed-service
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      nodePort: 31080
  selector:
    app: node1
