apiVersion: v1
kind: Service
metadata:
  name: til-akka-typed-api-service
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      nodePort: 31080
  selector:
    app: til-akka-typed

---
apiVersion: v1
kind: Service
metadata:
  name: dynamodb-local-service
spec:
  type: LoadBalancer
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      nodePort: 30000
  selector:
    app: dynamodb-local

---
apiVersion: v1
kind: Service
metadata:
  name: dynamodb-admin-service
spec:
  type: LoadBalancer
  ports:
    - port: 8001
      targetPort: 8001
      protocol: TCP
      nodePort: 30001
  selector:
    app: dynamodb-admin
