name: Sample Delivery

on:
  release:
    types: [published]

jobs:
  push_to_registry:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    permissions:
      packages: write # パッケージの操作権限を設定（Docker イメージのプッシュに必要）
      contents: read # リポジトリの内容を読み取る権限
      attestations: write # ビルド成果物の認証情報の設定に必要
      id-token: write # ビルド成果物の認証情報の設定に必要
    defaults:
      run:
        working-directory: sample
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: kuramapommel/til-akka-typed

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

    #   - name: Generate artifact attestation
    #     uses: actions/attest-build-provenance@v1
    #     with:
    #       subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
    #       subject-digest: ${{ steps.push.outputs.digest }}
    #       push-to-registry: true
